export const CI_WORKFLOW_TEMPLATE = [
  'name: CI/CD Pipeline',
  'on:',
  '  push:',
  '    branches: [main]',
  '  pull_request:',
  '    branches: [main]',
  '  schedule:',
  '    - cron: "0 */6 * * *"',
  'jobs:',
  '  test:',
  '    runs-on: ubuntu-latest',
  '    steps:',
  '      - uses: actions/checkout@v4',
  '      - name: Install Postman CLI',
  '        run: curl -o- "https://dl-cli.pstmn.io/install/unix.sh" | sh',
  '      - name: Login to Postman CLI',
  "        run: postman login --with-api-key \\${{ secrets.POSTMAN_API_KEY }}",
  '      - name: Run Smoke Tests',
  "        run: postman collection run \\${{ vars.POSTMAN_SMOKE_COLLECTION_UID }} -e \\${{ vars.POSTMAN_ENVIRONMENT_UID }} --env-var baseUrl=\\${{ vars.RUNTIME_BASE_URL || vars.DEV_GW_URL }} --report-events --env-var \"\\${{ vars.CI_ENVIRONMENT || 'Production' }}\"",
  '      - name: Run Contract Tests',
  "        run: postman collection run \\${{ vars.POSTMAN_CONTRACT_COLLECTION_UID }} -e \\${{ vars.POSTMAN_ENVIRONMENT_UID }} --env-var baseUrl=\\${{ vars.RUNTIME_BASE_URL || vars.DEV_GW_URL }} --report-events --env-var \"\\${{ vars.CI_ENVIRONMENT || 'Production' }}\"",
  ''
].join('\\n');
